### ISSUE TITLE
NASCAR 99 and NASCAR 2000

### ISSUE THREAD

**Issue by Nico976l** [Luciano2018/Nintendo64#1]
In both games there is a big green and blue bar over half the screen during racing restricting view of the track and there is a data loss warning when you start the game for the first time

**Comment by PIBSAS** [comment]
Both roms are ok, tested on lr-mupen64plus https://docs.libretro.com/library/mupen64plus/, this repository is only for share roms, im not develop the roms. check your emulator, there are different options to choose if you are using Raspberry Pi, and save core option for this particulary rom, because the core that you are using presume works fine with the rest.

**Comment by PIBSAS** [comment]
How to save per rom choice for the 3 OS noormally used:
RetroPie:
https://retropie.org.uk/docs/RetroArch-Core-Options/
Batocera(This one have screenshots make more eeasy to see the menu option):
https://wiki.batocera.org/advanced_retroarch_settings

Recalbox(But is more easy the way related on batocera(a fork   of recalbox):
https://wiki.recalbox.com/en/tutorials/controllers/configuration-of-customized-buttons/create-custom-configuration-per-emulator

**Comment by Nico976l** [comment]
It might just be the emulator I am using a web based emulator

**Comment by PIBSAS** [comment]
On the phone retroarch plus, or this websites:
https://www.retrogames.cc/n64-games/nascar-99-europe-en-fr-de.html

https://myemulator.online/nintendo-64/nascar-2000

no need roms
